### ISSUE TITLE
Add Python 3.13 support

### ISSUE THREAD

**Issue by rtibbles** [learningequality/morango#230]
```[tasklist]
### Tasks
- [x] Add support for the as yet unreleased Python 3.13
- [x] Add to CI version matrix
- [ ] Ensure all tests pass
```
